---
title: 'Clonal evolution: CLL to Richter transformation'
author: "Ramon Massoni-Badosa"
date: "2021/04/09"
output: 
  BiocStyle::html_document:
    toc: true
    toc_float: true
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, out.width = "100%", fig.align='center', 
                      message=FALSE, warning = FALSE)
options(width = 1200)
```


# Introduction

The purpose of this notebook is to visualize the clonal transcriptomic evolution in Richter syndrome.


# Pre-processing

## Load packages

```{r}
library(Seurat)
library(SeuratWrappers)
library(harmony)
library(tidyverse)
```


## Define parameters

```{r}
# Paths
path_to_12 <- here::here("results/R_objects/6.seurat_annotated_12.rds")
path_to_19 <- here::here("results/R_objects/6.seurat_annotated_19.rds")
path_to_63 <- here::here("results/R_objects/patient_63/3.seurat_annotated.rds")
path_to_365 <- here::here("results/R_objects/6.seurat_annotated_365.rds")
path_to_3299 <- here::here("results/R_objects/6.seurat_annotated_3299.rds")


# Colors
color_palette <- c("black", "gray", "red", "yellow", "violet", "green4",
                   "blue", "mediumorchid2", "coral2", "blueviolet",
                   "indianred4", "deepskyblue1", "dimgray", "deeppink1",
                   "green", "lightgray", "hotpink1")


# Source functions
source(here::here("bin/utils.R"))
```


## Load data

```{r}
paths_to_load <- c(
  "12" = path_to_12,
  "19" = path_to_19,
  "63" = path_to_63,
  "365" = path_to_365,
  "3299" = path_to_3299
)
seurat_list <- purrr::map(paths_to_load, readRDS)
seurat_list
purrr::map(seurat_list, DimPlot, cols = color_palette)
```


# Clonal evolution

## UMAPs splitted by time point

```{r fig.wide=TRUE}
seurat_list <- purrr::map(seurat_list, function(seurat_obj) {
  seurat_obj@meta.data <- seurat_obj@meta.data %>%
    mutate(sample_description_RM = str_c(
      time_point,
      sample_description_FN,
      sep = "_"
    ))
  seurat_obj
})
umaps_time_points <- purrr::map(names(seurat_list), function(x) {
  p <- plot_split_umap(seurat_list[[x]], "sample_description_RM", pt_size = 0.5) +
    ggtitle(x) +
    theme(plot.title = element_text(size = 13, hjust = 0.5, face = "bold"))
  p
})
names(umaps_time_points) <- names(seurat_list)
umaps_time_points
```


## Stacked bar plots

Let us start by computing the proportions of clons across time points:

```{r}
proportions_dfs <- purrr::map(seurat_list, function(seurat_obj) {
  df <- seurat_obj@meta.data %>%
    select("sample_description_RM", "annotation_final") %>%
    group_by(sample_description_RM, annotation_final) %>%
    summarise(n_cells = n()) %>%
    ungroup() %>%
    group_by(sample_description_RM) %>%
    mutate(n_cells_total = sum(n_cells)) %>%
    ungroup() %>%
    mutate(percentage_cells = round(n_cells / n_cells_total * 100, 3))
  df
})
DT::datatable(proportions_dfs$`12`)
DT::datatable(proportions_dfs$`19`)
DT::datatable(proportions_dfs$`63`)
DT::datatable(proportions_dfs$`365`)
DT::datatable(proportions_dfs$`3299`)
```

Plots:

```{r}
stacked_bars_ggs <- purrr::map(names(proportions_dfs), function(x) {
  p <- proportions_dfs[[x]] %>%
    ggplot(aes(sample_description_RM, percentage_cells, fill = annotation_final)) +
      geom_col() +
      ggtitle(x) +
      labs(x = "", y = "Percentage of Cells (%)", fill = "") + 
      scale_fill_manual(values = color_palette) +
      theme_bw() +
      theme(
        plot.title = element_text(size = 13, hjust = 0.5, face = "bold"),
        axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)
      )
  p
})
names(stacked_bars_ggs) <- names(seurat_list)
stacked_bars_ggs
```



# Session Inforamation

```{r}
sessionInfo()
```

