---
title: 'Create Accessibility Matrix'
author: "Ramon Massoni-Badosa"
date: "2021/04/09"
output: 
  BiocStyle::html_document:
    toc: true
    toc_float: true
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, out.width = "100%", fig.align='center', 
                      message=FALSE, warning = FALSE)
options(width = 1200)
```


# Introduction

Here we will call cells, call peaks and create the accessibility matrix.


# Pre-processing

## Load packages

```{r}
library(Seurat)
library(Signac)
library(EnsDb.Hsapiens.v86)
library(GenomicRanges)
library(GEOquery)
library(tidyverse)
library(glue)
```


## Define parameters

```{r}
# Paths
frag_path <- here::here("data/Penter2021/scATAC-seq")
macs_path <- "/apps/MACS2/20160309/bin/macs2"
path_to_mat <- here::here("7-revision/Penter2021/scATAC-seq/tmp/mat_tmp.rds")
path_to_peaks <- here::here("7-revision/Penter2021/scATAC-seq/tmp/combined_peaks_tmp.rds")
path_to_frags <- here::here("7-revision/Penter2021/scATAC-seq/tmp/frag_objs_tmp.rds")


# Parameters
n_barcodes <- 30000
max_peak_width <- 10000
min_peak_width <- 20
```


# Call cells

```{r}
gsm_dirs <- frag_path %>%
  list.dirs(full.names = FALSE) %>%
  str_subset("^GSM")
n_frag_dfs <- purrr::map(gsm_dirs, function(x) {
  path <- list.files(
    glue("{frag_path}/{x}"),
    full.names = TRUE,
    pattern = "fragments_per_cell.txt"
  )
  df <- read_delim(path, col_names = c("cell_barcode", "n_fragments"))
  df
})
names(n_frag_dfs) <- gsm_dirs
n_frag_df <- bind_rows(n_frag_dfs, .id = "dataset_id")
n_frag_df <- n_frag_df %>%
  arrange(desc(n_fragments)) %>%
  mutate(position = 1:nrow(n_frag_df))
(n_frag_gg <- n_frag_df %>%
  ggplot(aes(position, n_fragments)) +
    geom_line() +
    labs(x = "barcodes", y = "Number of Fragments") +
    scale_x_log10() +
    scale_y_log10() +
    theme_bw() +
    geom_vline(xintercept = n_barcodes, linetype = "dashed", color = "red"))
sel_cells <- n_frag_df %>%
  filter(position <= n_barcodes) %>%
  select("dataset_id", "cell_barcode")
```


# Call peaks

```{r}
frag_objs <- purrr::map(gsm_dirs, function(x) {
  path <- list.files(
    glue("{frag_path}/{x}"),
    full.names = TRUE,
    pattern = "_fragments.tsv.gz$"
  )
  cells <- sel_cells[sel_cells$dataset_id == x, "cell_barcode", drop = TRUE]
  frag_obj <- CreateFragmentObject(path, cells = cells)
  frag_obj
})
names(frag_objs) <- gsm_dirs
peaks_list <- purrr::map(frag_objs, function(x) {
  peaks <- CallPeaks(x, macs2.path = macs_path)
  peaks
})
combined_peaks <- GenomicRanges::reduce(c(
  peaks_list$GSM4982189,
  peaks_list$GSM4982190,
  peaks_list$GSM4982191,
  peaks_list$GSM4982192,
  peaks_list$GSM4982193,
  peaks_list$GSM4982194,
  peaks_list$GSM4982195,
  peaks_list$GSM4982196,
  peaks_list$GSM4982197
))
combined_peaks <- keepStandardChromosomes(
  combined_peaks,
  pruning.mode = "coarse"
)
combined_peaks <- subsetByOverlaps(
  x = combined_peaks,
  ranges = blacklist_hg38_unified,
  invert = TRUE
)
peak_widths <- width(combined_peaks)
peak_widths %>%
  as.data.frame() %>%
  setNames("width") %>%
  ggplot(aes(x = width)) +
    geom_histogram(bins = 30) +
    geom_vline(
      xintercept = c(min_peak_width, max_peak_width),
      linetype = "dashed",
      color = "red"
    ) +
    theme_classic()
peak_mask <- peak_widths < max_peak_width & peak_widths > min_peak_width
combined_peaks <- combined_peaks[peak_mask]
```


# Create accessibility matrix

```{r}
mat <- FeatureMatrix(
  fragments = frag_objs,
  features = combined_peaks,
  cells = sel_cells$cell_barcode
)
```


# Save

```{r}
saveRDS(mat, path_to_mat)
saveRDS(combined_peaks, path_to_peaks)
saveRDS(frag_objs, path_to_frags)
```


# Session Information

```{r}
sessionInfo()
```

